apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  ports:
    - port: 5153
      targetPort: 5153
  selector:
    app: coworking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coworking
  template:
    metadata:
      labels:
        app: coworking
    spec:
      containers:
      - name: coworking
        image: 914394607422.dkr.ecr.us-east-1.amazonaws.com/coworking:latest   # your ECR image
        ports:
        - containerPort: 5153
        envFrom:
        - configMapRef:
            name: coworking-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: coworking-secret
              key: DB_PASSWORD
